POST http://localhost:3000/api/register

{
    "username": "test",
    "email": "ndiakhate01998@gmail.com",
    "password": "test111",
    "confirmPassword": "test111",
}


# POST http://localhost:3000/api/send

# {
#     "recipient":["ndiakhate01998@gmail.com"],
#     "subject": "test",
#     "content": "<p> Hello world </p>"
# }


# POST http://localhost:3000/api/confirmation-email

# {
# }
